server:
  port: 8083

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

jwt:
  validity: {5 * 60 * 60}
  secret:

mockdata: false

user-service-uri:
cluster-service-uri:
results-storage-path: /tmp/hafenkran/results

service-user:
  name:
  password: