server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  validity: {5 * 60 * 60}
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB

mockdata: true

user-service-uri: http://localhost:8081
cluster-service-uri: http://localhost:8082
results-storage-path: /tmp/hafenkran/results

service-user:
  name: service
  password: test
  secret: secretToken

metrics:
  frequency: 60
  initial-delay: 120